const proj = [
	{
		name: 'DOM Manipulation Practice App',
		creator: 'Jamie Reardon',
		date: 'Thursday May 5, 2020',
		description: 'The project is based on the beloved Treehouse landing page for the techdegree. The page contains three widgets that you will manipulate with JavaScript to complete the functionlity to the page.',
		tags: 'expert jamie dom manipulation practice app javascript treehouse landing page widget',
		readme: 'https://github.com/jmereardon17/techdegree-slack-challenges-project-01/blob/master/README.md',
		download: 'https://github.com/jmereardon17/techdegree-slack-challenges-project-01/archive/master.zip',
		timeToComplete: '2 hours',
		html: false,
		css: false,
		javascript: true
	},
	{
		name: 'firebasejs (code the mockup!)',
		creator: 'Dustin Usey',
		date: 'Tuesday May 12, 2020',
		description: "You're working for a company as a front-end developer. Your boss tells you that your team is putting the finishing touches on a plugin they've been developing; fireboxjs. The design team has created a mockup for the landing page for this plugin and your boss needs you to code it out with just HTML and CSS!",
		tags: 'beginner dustin from mockup to code html css plugin frontend landing firebasejs',
		readme: 'https://github.com/dustinusey/firebasejs/blob/master/README.md',
		download: 'https://github.com/dustinusey/firebasejs/archive/master.zip',
		timeToComplete: '2 hours',
		html: true,
		css: true,
		javascript: false
	},
	{
		name: 'Momentum (code the mockup!)',
		creator: 'Dustin Usey',
		date: 'Tuesday May 12, 2020',
		description: "You're working for a company as a front-end developer. Your boss tells you that your team is putting the finishing touches on a website they've been developing; Momentum. The design team has created a mockup for the beta testing landing page for this website and your boss needs you to code it out with just HTML and CSS!",
		tags: 'beginner dustin from mockup to code html css plugin frontend landing momentum',
		readme: 'https://github.com/dustinusey/Momentum/blob/master/README.md',
		download: 'https://github.com/dustinusey/momentum/archive/master.zip',
		timeToComplete: '1 hour',
		html: true,
		css: true,
		javascript: false
	},
	{
		name: 'iOS Settings Design',
		creator: 'Dustin Usey',
		date: 'Thursday May 14, 2020',
		description: "With this Mockup code challenge, I challenge you to take the iOS Settings as shown in the mockup and recreate it using HTML and CSS! This is a great time to use flexbox or even CSS Grid to structure your settings items.",
		tags: 'beginner dustin from mockup to code html css frontend ios settings darkmode flex grid',
		readme: 'https://github.com/dustinusey/iOS_Settings/blob/master/README.md',
		download: 'https://github.com/dustinusey/iOS_Settings/archive/master.zip',
		timeToComplete: '2 hours',
		html: true,
		css: true,
		javascript: false
	},
	{
		name: 'Randomized Meal Planner',
		creator: 'Jamie Reardon',
		date: '19/05/2020',
		description: 'Create a randomized meal planner that you can use to generate a weekly meal plan for the week.',
		tags: 'HTML CSS JavaScript meal mealplan random jamie',
		readme: 'https://github.com/jmereardon17/techdegree-slack-challenges-project-02/blob/master/README.md',
		download: 'https://github.com/jmereardon17/techdegree-slack-challenges-project-02/archive/master.zip',
		timeToComplete: '3 Hours',
		html: true,
		css: true,
		javascript: true
	},
]