const data = [
    {
        project_name: 'DOM Manipulation Practice',
        project_length:  '2 hours',
        project_date: 'Tuesday May 5, 2020',
        project_creator: 'Jamie Reardon',
        project_image: './img/bg/card8.png',
        project_desc: "The project is based on the beloved Treehouse landing page for the techdegree. The page contains three widgets that you will manipulate with JavaScript to complete the functionlity to the page.",
        project_html: true,
        project_css: true,
        project_js: true,
        project_instructions: 'https://github.com/jmereardon17/techdegree-slack-challenges-project-01/blob/master/README.md',
        project_download: 'https://github.com/jmereardon17/techdegree-slack-challenges-project-01/archive/master.zip',
    },
    {
        project_name: 'firebaseJS (mockup)',
        project_length:  '2 hours',
        project_date: 'Tuesday May 12, 2020',
        project_creator: 'Dustin Usey',
        project_image: './img/bg/card7.png',
        project_desc: "You're working for a company as a front-end developer. Your boss tells you that your team is putting the finishing touches on a plugin they've been developing; fireboxjs. The design team has created a mockup for the landing page for this plugin and your boss needs you to code it out with just HTML and CSS!",
        project_html: true,
        project_css: true,
        project_js: false,
        project_instructions: 'https://github.com/dustinusey/firebasejs/blob/master/README.md',
        project_download: 'https://github.com/dustinusey/firebasejs/archive/master.zip',
    },
    {
        project_name: 'Momentum (mockup)',
        project_length:  '1 hour',
        project_date: 'Tuesday May 12, 2020',
        project_creator: 'Dustin Usey',
        project_image: './img/bg/card6.png',
        project_desc: "You're working for a company as a front-end developer. Your boss tells you that your team is putting the finishing touches on a website they've been developing; Momentum. The design team has created a mockup for the beta testing landing page for this website and your boss needs you to code it out with just HTML and CSS!",
        project_html: true,
        project_css: true,
        project_js: false,
        project_instructions: 'https://github.com/dustinusey/Momentum/blob/master/README.md',
        project_download: 'https://github.com/dustinusey/momentum/archive/master.zip',
    },
    {
        project_name: 'iOS Settings Design (mockup)',
        project_length:  '2 hours',
        project_date: 'Thursday May 14, 2020',
        project_creator: 'Dustin Usey',
        project_image: './img/bg/card5.png',
        project_desc: 'With this Mockup code challenge, I challenge you to take the iOS Settings as shown in the mockup and recreate it using HTML and CSS! This is a great time to use flexbox or even CSS Grid to structure your settings items.',
        project_html: true,
        project_css: true,
        project_js: false,
        project_instructions: 'https://github.com/dustinusey/iOS_Settings/blob/master/README.md',
        project_download: 'https://github.com/dustinusey/iOS_Settings/archive/master.zip',
    },
    {
        project_name: 'Randomized Meal Planner',
        project_length:  '3 hours',
        project_date: 'Tuesday May 19, 2020',
        project_creator: 'Jamie Reardon',
        project_image: './img/bg/card4.png',
        project_desc: 'Create a randomized meal planner that you can use to generate a weekly meal plan for the week.',
        project_html: true,
        project_css: true,
        project_js: true,
        project_instructions: 'https://github.com/jmereardon17/techdegree-slack-challenges-project-02/blob/master/README.md',
        project_download: 'https://github.com/jmereardon17/techdegree-slack-challenges-project-02/archive/master.zip',
    },
    {
        project_name: 'CloudFlare (mockup)',
        project_length:  '4 hours',
        project_date: 'Tuesday June 2, 2020',
        project_creator: 'Dustin Usey',
        project_image: './img/bg/card3.png',
        project_desc: 'CloudFlare is a cloud storage software that will allow users to securely store their files in the cloud. You, as a frontend developer, will will need to recreate the mockup provided to give this web space a login page.',
        project_html: true,
        project_css: true,
        project_js: false,
        project_instructions: 'https://github.com/dustinusey/cloudflare/blob/master/README.md',
        project_download: 'https://github.com/dustinusey/cloudflare/archive/master.zip',
    },
    {
        project_name: 'featherLITE (mockup)',
        project_length:  '4 hours',
        project_date: 'Friday June 26, 2020',
        project_creator: 'Dustin Usey',
        project_image: './img/bg/card2.png',
        project_desc: 'Feather is a new note taking app that your company will be creating. The design team has given you mockups to code out a LITE version of this application. Are you up for the challenge?',
        project_html: true,
        project_css: true,
        project_js: true,
        project_instructions: 'https://github.com/dustinusey/featherLITE/blob/master/README.md',
        project_download: 'https://github.com/dustinusey/featherLITE/archive/master.zip',
    },
    {
        project_name: 'Social Media Challenge (mockup)',
        project_length:  '4 hours',
        project_date: 'Sunday July 5, 2020',
        project_creator: 'Dustin Usey',
        project_image: './img/bg/card1.png',
        project_desc: "You're comfortable in your coding skills and want to create the next best social media platform! You're given a mockup to follow to create this new platform with only HTML and CSS!",
        project_html: true,
        project_css: true,
        project_js: false,
        project_instructions: 'https://github.com/dustinusey/social-challenge/blob/master/README.md',
        project_download: 'https://github.com/dustinusey/social-challenge/archive/master.zip'
    },
    {
        project_name: 'Paws - Pet Adoption Website',
        project_length:  '2 hours',
        project_date: 'Saturday August 1, 2020',
        project_creator: 'Dustin Usey',
        project_image: './img/bg/card0.png',
        project_desc: "You're taking your freelancing skills to the streets and noticed a pet adoption agency doesn't have a website. You offer to create one for them and sell it.",
        project_html: true,
        project_css: true,
        project_js: false,
        project_instructions: 'https://github.com/dustinusey/Paws/blob/master/README.md',
        project_download: 'https://github.com/dustinusey/Paws/archive/master.zip'
    },
];
data.reverse();


